### ISSUE TITLE
Error with redis hash

### ISSUE THREAD

**Issue by pranny** [hharnisc/python-ddp#7]
I am having a meteor with redis combination. Alongwith a python ddp client listening to all "added" events. I am using redis Hash and encountering errors. Following pieces of code should be relevant.

```
// [Meteor] server/method.js
newSession: function(sessionId) {
    let session = {
      timestamp: Math.floor(Date.now() / 1000),
      ip_addr: '127.0.0.1',
    };
    sessionId = 'ms_' + sessionId;
    for( let key in session ) {
      Redis.hset( sessionId, key, session[key] );
    }
    return sessionId;
  },
```

My Python client is extremely simple and looks like this:

```
from DDPClient import DDPClient
import time

client = DDPClient('ws://127.0.0.1:3000/websocket', debug=False)

def added(collection, id, fields):
    sessionId = id.split('_')[1]
    client.call('validateSession', [sessionId], doSomething);

def connected():
    client.subscribe('all_sessions', [])

def doSomething(err, response):
    print '--'
    print response
    print err

client.on('added', added)
client.on('connected', connected)

client.connect()

# (sort of) hacky way to keep the client alive
# ctrl + c to kill the script
while True:
    try:
        time.sleep(1)
    except KeyboardInterrupt:
        break

client.unsubscribe('all_sessions')
```

Whenever the `newSession` method is called, I get an error at Python client as

```
Exception in thread WebSocketClient:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/ws4py/websocket.py", line 427, in run
    if not self.once():
  File "/Library/Python/2.7/site-packages/DDPClient.py", line 53, in once
    return super(DDPSocket, self).once()
  File "/Library/Python/2.7/site-packages/ws4py/websocket.py", line 305, in once
    if not self.process(b):
  File "/Library/Python/2.7/site-packages/ws4py/websocket.py", line 377, in process
    self.received_message(s.message)
  File "/Library/Python/2.7/site-packages/DDPClient.py", line 41, in received_message
    self.emit('received_message', data)
  File "/Library/Python/2.7/site-packages/pyee/__init__.py", line 113, in emit
    f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/DDPClient.py", line 162, in received_message
    data = ejson.loads(str(data))
  File "/Library/Python/2.7/site-packages/ejson/__init__.py", line 132, in loads
    return json.loads(obj, *args, cls=kwargs.pop('cls', EJSONDecoder), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/Library/Python/2.7/site-packages/ejson/__init__.py", line 126, in decode
    return self._decode(o)
  File "/Library/Python/2.7/site-packages/ejson/__init__.py", line 117, in _decode
    return {k: self._decode(v) for k, v in o.items()}
  File "/Library/Python/2.7/site-packages/ejson/__init__.py", line 117, in <dictcomp>
    return {k: self._decode(v) for k, v in o.items()}
  File "/Library/Python/2.7/site-packages/ejson/__init__.py", line 117, in _decode
    return {k: self._decode(v) for k, v in o.items()}
  File "/Library/Python/2.7/site-packages/ejson/__init__.py", line 117, in <dictcomp>
    return {k: self._decode(v) for k, v in o.items()}
  File "/Library/Python/2.7/site-packages/ejson/__init__.py", line 111, in _decode
    raise UnknownTypeError(o["$type"])
UnknownTypeError: redis-hash
```

I suspect this is because the Redis data structure is a hash? Are redis-hash supported in python-ddp? I could probably use a stringify version of the session hash here, but i need a fast lookup on one of the keys, so prefer the hash way.

**Comment by pranny** [comment]
I just verified that if I change the DS from hash to String, it works great.
